//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.nap7.com")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.nap7.com", IsNullable=false)]
public partial class MongoDBConfiguration {
    
    private MongoDBConfigurationMongoDB mongoDBField;
    
    /// <remarks/>
    public MongoDBConfigurationMongoDB MongoDB {
        get {
            return this.mongoDBField;
        }
        set {
            this.mongoDBField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.nap7.com")]
public partial class MongoDBConfigurationMongoDB {
    
    private MongoDBConfigurationMongoDBMongoDBClient mongoDBClientField;
    
    /// <remarks/>
    public MongoDBConfigurationMongoDBMongoDBClient MongoDBClient {
        get {
            return this.mongoDBClientField;
        }
        set {
            this.mongoDBClientField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.nap7.com")]
public partial class MongoDBConfigurationMongoDBMongoDBClient {
    
    private string idField;
    
    private MongoDBConfigurationMongoDBMongoDBClientMode modeField;
    
    private bool modeFieldSpecified;
    
    private string connectionStringField;
    
    private string defaultDatabaseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public MongoDBConfigurationMongoDBMongoDBClientMode Mode {
        get {
            return this.modeField;
        }
        set {
            this.modeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ModeSpecified {
        get {
            return this.modeFieldSpecified;
        }
        set {
            this.modeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string ConnectionString {
        get {
            return this.connectionStringField;
        }
        set {
            this.connectionStringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string DefaultDatabase {
        get {
            return this.defaultDatabaseField;
        }
        set {
            this.defaultDatabaseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.nap7.com")]
public enum MongoDBConfigurationMongoDBMongoDBClientMode {
    
    /// <remarks/>
    Read,
    
    /// <remarks/>
    Write,
    
    /// <remarks/>
    Full,
}
